
"""
    Copyright (C) <2010>  Autin L. TSRI
    
    This file git_upy/autodesk3dsmax/v2013/classIds.py is part of upy.

    upy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    upy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with upy.  If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
"""
"""
MaxPlus.ClassIds.AcmodGeomGeomBooladd
MaxPlus.ClassIds.AcmodGeomGeomBoolint
MaxPlus.ClassIds.AcmodGeomGeomBoolsub
MaxPlus.ClassIds.AcmodGeomGeomSimpagg
MaxPlus.ClassIds.AcmodShapeGeomEmboss
MaxPlus.ClassIds.AcmodShapeGeomHole
MaxPlus.ClassIds.AcmodShapeGeomInt
MaxPlus.ClassIds.AcmodShapeGeomReveal
MaxPlus.ClassIds.Acubic
MaxPlus.ClassIds.Add
MaxPlus.ClassIds.AdditiveEulerControl
MaxPlus.ClassIds.Affectregion
MaxPlus.ClassIds.Aggman
MaxPlus.ClassIds.Alpha
MaxPlus.ClassIds.AlphaBakeElement
MaxPlus.ClassIds.AlphaRenderElement
MaxPlus.ClassIds.AmbientocclusionBakeElement
MaxPlus.ClassIds.Angle
MaxPlus.ClassIds.Anisoshader
MaxPlus.ClassIds.ApplyvcUtil
MaxPlus.ClassIds.Arc
MaxPlus.ClassIds.AreaKernel
MaxPlus.ClassIds.AssignrefRest
MaxPlus.ClassIds.Atmospheric
MaxPlus.ClassIds.AtmosphericsRollupcfg
MaxPlus.ClassIds.AttachControl
MaxPlus.ClassIds.Avi
MaxPlus.ClassIds.AxisDisplay
MaxPlus.ClassIds.BakeElement
MaxPlus.ClassIds.BakeShell
MaxPlus.ClassIds.Basenode
MaxPlus.ClassIds.Baseobjappdata
MaxPlus.ClassIds.Baseobjappdatacursel
MaxPlus.ClassIds.Baseobjappdatalastsel
MaxPlus.ClassIds.BeautyRenderElement
MaxPlus.ClassIds.Bendosm
MaxPlus.ClassIds.BezfontLoader
MaxPlus.ClassIds.Bitmapdad
MaxPlus.ClassIds.BlendBakeElement
MaxPlus.ClassIds.Blinn
MaxPlus.ClassIds.Blur
MaxPlus.ClassIds.BmmColorcut
MaxPlus.ClassIds.BmmDither
MaxPlus.ClassIds.BmmFilter
MaxPlus.ClassIds.BmmIo
MaxPlus.ClassIds.BmmStorage
MaxPlus.ClassIds.Bmp
MaxPlus.ClassIds.Bmtex
MaxPlus.ClassIds.Bomb
MaxPlus.ClassIds.BombObject
MaxPlus.ClassIds.Bone
MaxPlus.ClassIds.BoneObj
MaxPlus.ClassIds.Boolcntrl
MaxPlus.ClassIds.Boolobj
MaxPlus.ClassIds.Boxgizmo
MaxPlus.ClassIds.Boxobj
MaxPlus.ClassIds.Camera
MaxPlus.ClassIds.Channel
MaxPlus.ClassIds.Checker
MaxPlus.ClassIds.Circle
MaxPlus.ClassIds.Cmtl
MaxPlus.ClassIds.CollisionFoInterface
MaxPlus.ClassIds.Colorcorrection
MaxPlus.ClassIds.Colpick
MaxPlus.ClassIds.CompleteBakeElement
MaxPlus.ClassIds.Composite
MaxPlus.ClassIds.CompositeMaterial
MaxPlus.ClassIds.Cone
MaxPlus.ClassIds.Container
MaxPlus.ClassIds.Cookie
MaxPlus.ClassIds.Crosfade
MaxPlus.ClassIds.CtrlColor
MaxPlus.ClassIds.CtrlColor24
MaxPlus.ClassIds.CtrlFloat
MaxPlus.ClassIds.CtrlFrgba
MaxPlus.ClassIds.CtrlInteger
MaxPlus.ClassIds.CtrlMasterpoint
MaxPlus.ClassIds.CtrlMatrix3
MaxPlus.ClassIds.CtrlMorph
MaxPlus.ClassIds.CtrlPoint2
MaxPlus.ClassIds.CtrlPoint3
MaxPlus.ClassIds.CtrlPoint4
MaxPlus.ClassIds.CtrlPos
MaxPlus.ClassIds.CtrlPosition
MaxPlus.ClassIds.CtrlQuat
MaxPlus.ClassIds.CtrlRotation
MaxPlus.ClassIds.CtrlScale
MaxPlus.ClassIds.CtrlShort
MaxPlus.ClassIds.CtrlUsertype
MaxPlus.ClassIds.CurveControl
MaxPlus.ClassIds.CustAttrib
MaxPlus.ClassIds.CustattribContainer
MaxPlus.ClassIds.Cycle
MaxPlus.ClassIds.Cylgizmo
MaxPlus.ClassIds.Cylinder
MaxPlus.ClassIds.Daylight
MaxPlus.ClassIds.DefSoundobj
MaxPlus.ClassIds.DefaultColpick
MaxPlus.ClassIds.Deflectmod
MaxPlus.ClassIds.Deflectobject
MaxPlus.ClassIds.DeformObj
MaxPlus.ClassIds.Delete
MaxPlus.ClassIds.DelrefRest
MaxPlus.ClassIds.Derivob
MaxPlus.ClassIds.DiffuseBakeElement
MaxPlus.ClassIds.DirLight
MaxPlus.ClassIds.DisplaceObject
MaxPlus.ClassIds.DisplaceWsm
MaxPlus.ClassIds.Displaceosm
MaxPlus.ClassIds.DisplayPanelRollupcfg
MaxPlus.ClassIds.Dmtl
MaxPlus.ClassIds.Dmtl2
MaxPlus.ClassIds.Donut
MaxPlus.ClassIds.Doublesided
MaxPlus.ClassIds.Dummy
MaxPlus.ClassIds.DummyControl
MaxPlus.ClassIds.Dummychannel
MaxPlus.ClassIds.EaseList
MaxPlus.ClassIds.EditPolyModifier
MaxPlus.ClassIds.EditableCvcurve
MaxPlus.ClassIds.EditableFpcurve
MaxPlus.ClassIds.EditableSurf
MaxPlus.ClassIds.Edittriobj
MaxPlus.ClassIds.EffectsRollupcfg
MaxPlus.ClassIds.Ellipse
MaxPlus.ClassIds.Epolyobj
MaxPlus.ClassIds.EulerControl
MaxPlus.ClassIds.ExposeWorldTransform
MaxPlus.ClassIds.ExprFloatControl
MaxPlus.ClassIds.ExprP3Control
MaxPlus.ClassIds.ExprPosControl
MaxPlus.ClassIds.ExprRotControl
MaxPlus.ClassIds.ExprScaleControl
MaxPlus.ClassIds.Extrudeosm
MaxPlus.ClassIds.Fade
MaxPlus.ClassIds.Falloff
MaxPlus.ClassIds.Fb
MaxPlus.ClassIds.Ffd22
MaxPlus.ClassIds.Ffd33
MaxPlus.ClassIds.Ffd44
MaxPlus.ClassIds.Ffdnmoscyl
MaxPlus.ClassIds.Ffdnmossquare
MaxPlus.ClassIds.Ffdnmwscyl
MaxPlus.ClassIds.FfdnmwscylMod
MaxPlus.ClassIds.Ffdnmwssquare
MaxPlus.ClassIds.FfdnmwssquareMod
MaxPlus.ClassIds.FilterKernel
MaxPlus.ClassIds.FitpointPlane
MaxPlus.ClassIds.Flic
MaxPlus.ClassIds.FloatMotion
MaxPlus.ClassIds.FloatWireControl
MaxPlus.ClassIds.FloatlayerControl
MaxPlus.ClassIds.Floatlimitctrl
MaxPlus.ClassIds.FloatlistControl
MaxPlus.ClassIds.FloatnoiseControl
MaxPlus.ClassIds.Flt
MaxPlus.ClassIds.Fog
MaxPlus.ClassIds.FrontendControl
MaxPlus.ClassIds.FspotLight
MaxPlus.ClassIds.GenDerivob
MaxPlus.ClassIds.GenModapp
MaxPlus.ClassIds.GenericAmsolid
MaxPlus.ClassIds.GenericShape
MaxPlus.ClassIds.Geomobject
MaxPlus.ClassIds.GlobalVarTvnode
MaxPlus.ClassIds.Glow
MaxPlus.ClassIds.Gnormal
MaxPlus.ClassIds.Gradient
MaxPlus.ClassIds.Gravitymod
MaxPlus.ClassIds.Gravityobject
MaxPlus.ClassIds.GridOsnap
MaxPlus.ClassIds.Gridhelp
MaxPlus.ClassIds.Gsphere
MaxPlus.ClassIds.Gup
MaxPlus.ClassIds.HalfRound
MaxPlus.ClassIds.Hedra
MaxPlus.ClassIds.HeightBakeElement
MaxPlus.ClassIds.Helix
MaxPlus.ClassIds.Helper
MaxPlus.ClassIds.HierarchyPanelRollupcfg
MaxPlus.ClassIds.HybridinterpColor
MaxPlus.ClassIds.HybridinterpFloat
MaxPlus.ClassIds.HybridinterpFrgba
MaxPlus.ClassIds.HybridinterpPoint2
MaxPlus.ClassIds.HybridinterpPoint3
MaxPlus.ClassIds.HybridinterpPoint4
MaxPlus.ClassIds.HybridinterpPosition
MaxPlus.ClassIds.HybridinterpRotation
MaxPlus.ClassIds.HybridinterpScale
MaxPlus.ClassIds.IExecCtrlBypassTreeView
MaxPlus.ClassIds.IExecEvalSoaTime
MaxPlus.ClassIds.IExecGetSoaState
MaxPlus.ClassIds.Ifl
MaxPlus.ClassIds.IkSolver
MaxPlus.ClassIds.Ikchaincontrol
MaxPlus.ClassIds.Ikcontrol
MaxPlus.ClassIds.Ikmaster
MaxPlus.ClassIds.Ikslave
MaxPlus.ClassIds.IlluminanceRenderElement
MaxPlus.ClassIds.Img
MaxPlus.ClassIds.IndirectReftargContainer
MaxPlus.ClassIds.JiggleP3
MaxPlus.ClassIds.JigglePos
MaxPlus.ClassIds.Jpeg
MaxPlus.ClassIds.Layer
MaxPlus.ClassIds.LayeroutputControl
MaxPlus.ClassIds.Light
MaxPlus.ClassIds.LightBakeElement
MaxPlus.ClassIds.LightingRenderElement
MaxPlus.ClassIds.LightscapeLight
MaxPlus.ClassIds.Linearshape
MaxPlus.ClassIds.LininterpFloat
MaxPlus.ClassIds.LininterpPosition
MaxPlus.ClassIds.LininterpRotation
MaxPlus.ClassIds.LininterpScale
MaxPlus.ClassIds.LinkTimeControl
MaxPlus.ClassIds.Linkctrl
MaxPlus.ClassIds.Linktmctrl
MaxPlus.ClassIds.Linwave
MaxPlus.ClassIds.LinwaveObject
MaxPlus.ClassIds.LinwaveOmod
MaxPlus.ClassIds.LocalEulerControl
MaxPlus.ClassIds.Lockmat
MaxPlus.ClassIds.LoftDefcurve
MaxPlus.ClassIds.LoftGeneric
MaxPlus.ClassIds.Loftobj
MaxPlus.ClassIds.LookatCam
MaxPlus.ClassIds.LookatConstraint
MaxPlus.ClassIds.LookatControl
MaxPlus.ClassIds.LsAreaLight
MaxPlus.ClassIds.LsAreaLightTarget
MaxPlus.ClassIds.LsArealightcustattrib
MaxPlus.ClassIds.LsCylinderLight
MaxPlus.ClassIds.LsCylinderLightTarget
MaxPlus.ClassIds.LsDiscLight
MaxPlus.ClassIds.LsDiscLightTarget
MaxPlus.ClassIds.LsLinearLight
MaxPlus.ClassIds.LsLinearLightTarget
MaxPlus.ClassIds.LsPointLight
MaxPlus.ClassIds.LsPointLightTarget
MaxPlus.ClassIds.LsSphereLight
MaxPlus.ClassIds.LsSphereLightTarget
MaxPlus.ClassIds.Luminaire
MaxPlus.ClassIds.MakerefRest
MaxPlus.ClassIds.MappableObj
MaxPlus.ClassIds.Marble
MaxPlus.ClassIds.Mask
MaxPlus.ClassIds.MasterblockSuper
MaxPlus.ClassIds.Masterlayercontrolmanager
MaxPlus.ClassIds.MasterlistControl
MaxPlus.ClassIds.Mastermaxclip
MaxPlus.ClassIds.Masterpointcont
MaxPlus.ClassIds.Material
MaxPlus.ClassIds.MaterialidRenderElement
MaxPlus.ClassIds.Materialosm
MaxPlus.ClassIds.Matte
MaxPlus.ClassIds.Maxopenexr
MaxPlus.ClassIds.MaxscriptUtility
MaxPlus.ClassIds.MaxscriptWrapper
MaxPlus.ClassIds.Mblur
MaxPlus.ClassIds.Medit
MaxPlus.ClassIds.MeshCollision
MaxPlus.ClassIds.MeshExtrudeCluster
MaxPlus.ClassIds.MeshExtrudeLocal
MaxPlus.ClassIds.Meshdeformpw
MaxPlus.ClassIds.Meshselect
MaxPlus.ClassIds.Metal
MaxPlus.ClassIds.Mirror
MaxPlus.ClassIds.Mix
MaxPlus.ClassIds.Mixmat
MaxPlus.ClassIds.Modapp
MaxPlus.ClassIds.Morphobj
MaxPlus.ClassIds.MotCapDev
MaxPlus.ClassIds.MotCapDevbinding
MaxPlus.ClassIds.MotionPanelRollupcfg
MaxPlus.ClassIds.MpassCamEffect
MaxPlus.ClassIds.Mpg
MaxPlus.ClassIds.MrShaderClassIdDefunct
MaxPlus.ClassIds.MtlCategory
MaxPlus.ClassIds.MtlLib
MaxPlus.ClassIds.MtlbaseLib
MaxPlus.ClassIds.MultList
MaxPlus.ClassIds.Multi
MaxPlus.ClassIds.MultiMaterial
MaxPlus.ClassIds.Multioutputtotexmap
MaxPlus.ClassIds.Negative
MaxPlus.ClassIds.Newbool
MaxPlus.ClassIds.Newshaders
MaxPlus.ClassIds.Ngon
MaxPlus.ClassIds.Nodemonitor
MaxPlus.ClassIds.Nodetransformmonitor
MaxPlus.ClassIds.Noise
MaxPlus.ClassIds.Normalosm
MaxPlus.ClassIds.NormalsElement
MaxPlus.ClassIds.Notetrack
MaxPlus.ClassIds.Nurbsobj
MaxPlus.ClassIds.ObjectidRenderElement
MaxPlus.ClassIds.ObrefModapp
MaxPlus.ClassIds.Oldparticlecache
MaxPlus.ClassIds.Oldpointcache
MaxPlus.ClassIds.Oldpointcachewsm
MaxPlus.ClassIds.OmniLight
MaxPlus.ClassIds.Optimizeosm
MaxPlus.ClassIds.OrientationConstraint
MaxPlus.ClassIds.Osm
MaxPlus.ClassIds.Osnap
MaxPlus.ClassIds.Output
MaxPlus.ClassIds.Painterinterface
MaxPlus.ClassIds.Paintlayermod
MaxPlus.ClassIds.ParameterBlock
MaxPlus.ClassIds.ParameterBlock2
MaxPlus.ClassIds.ParticleSys
MaxPlus.ClassIds.Patchdeformpw
MaxPlus.ClassIds.Patchgrid
MaxPlus.ClassIds.Patchobj
MaxPlus.ClassIds.PathControl
MaxPlus.ClassIds.Pdalpha
MaxPlus.ClassIds.PfItemSub
MaxPlus.ClassIds.PfObjectSub
MaxPlus.ClassIds.PfOperator3dSub
MaxPlus.ClassIds.PfOperatorSub
MaxPlus.ClassIds.PfSubclassIdPartb
MaxPlus.ClassIds.PfTest3dSub
MaxPlus.ClassIds.PfTestSub
MaxPlus.ClassIds.Phong
MaxPlus.ClassIds.Pipe
MaxPlus.ClassIds.PlanarCollision
MaxPlus.ClassIds.Plane
MaxPlus.ClassIds.Platet
MaxPlus.ClassIds.Point3Motion
MaxPlus.ClassIds.Point3WireControl
MaxPlus.ClassIds.Point3layerControl
MaxPlus.ClassIds.Point3listControl
MaxPlus.ClassIds.Point3noiseControl
MaxPlus.ClassIds.Point4WireControl
MaxPlus.ClassIds.Point4layerControl
MaxPlus.ClassIds.Point4listControl
MaxPlus.ClassIds.Pointcacheosm
MaxPlus.ClassIds.Pointcachewsm
MaxPlus.ClassIds.Pointhelp
MaxPlus.ClassIds.Polyobj
MaxPlus.ClassIds.PosMotion
MaxPlus.ClassIds.PositionConstraint
MaxPlus.ClassIds.PositionWireControl
MaxPlus.ClassIds.PositionnoiseControl
MaxPlus.ClassIds.PoslayerControl
MaxPlus.ClassIds.PoslistControl
MaxPlus.ClassIds.Projectionmod
MaxPlus.ClassIds.Prothelp
MaxPlus.ClassIds.PrsControl
MaxPlus.ClassIds.Pyramid
MaxPlus.ClassIds.QuarterRound
MaxPlus.ClassIds.R25Sampler
MaxPlus.ClassIds.Radiosity
MaxPlus.ClassIds.Rain
MaxPlus.ClassIds.Rectangle
MaxPlus.ClassIds.RefMaker
MaxPlus.ClassIds.RefTarget
MaxPlus.ClassIds.ReflectRefractBakeElement
MaxPlus.ClassIds.ReftargContainer
MaxPlus.ClassIds.Reftargmonitor
MaxPlus.ClassIds.RenderEffect
MaxPlus.ClassIds.RenderElement
MaxPlus.ClassIds.Renderer
MaxPlus.ClassIds.Rgbmult
MaxPlus.ClassIds.Ringarray
MaxPlus.ClassIds.Rla
MaxPlus.ClassIds.RotMotion
MaxPlus.ClassIds.RotationWireControl
MaxPlus.ClassIds.RotationnoiseControl
MaxPlus.ClassIds.RotlayerControl
MaxPlus.ClassIds.RotlistControl
MaxPlus.ClassIds.Rpf
MaxPlus.ClassIds.Sampler
MaxPlus.ClassIds.ScaleMotion
MaxPlus.ClassIds.ScaleWireControl
MaxPlus.ClassIds.ScalelayerControl
MaxPlus.ClassIds.ScalelistControl
MaxPlus.ClassIds.ScalenoiseControl
MaxPlus.ClassIds.Scene
MaxPlus.ClassIds.SceneExport
MaxPlus.ClassIds.SceneImport
MaxPlus.ClassIds.SchematicviewUtility
MaxPlus.ClassIds.Selectosm
MaxPlus.ClassIds.Shader
MaxPlus.ClassIds.ShadowBakeElement
MaxPlus.ClassIds.ShadowType
MaxPlus.ClassIds.ShadowsRenderElement
MaxPlus.ClassIds.Shape
MaxPlus.ClassIds.SimpleCam
MaxPlus.ClassIds.Simpleosmtowsm
MaxPlus.ClassIds.Simpleosmtowsm2
MaxPlus.ClassIds.Sinewave
MaxPlus.ClassIds.SinewaveObject
MaxPlus.ClassIds.SinewaveOmod
MaxPlus.ClassIds.Skewosm
MaxPlus.ClassIds.Skin
MaxPlus.ClassIds.SlaveControl
MaxPlus.ClassIds.SlavefloatControl
MaxPlus.ClassIds.Slavematrix3Control
MaxPlus.ClassIds.Slavepoint3Control
MaxPlus.ClassIds.Slavepoint4Control
MaxPlus.ClassIds.SlaveposControl
MaxPlus.ClassIds.SlaverotationControl
MaxPlus.ClassIds.SlavescaleControl
MaxPlus.ClassIds.Smoothosm
MaxPlus.ClassIds.Snow
MaxPlus.ClassIds.Soundobj
MaxPlus.ClassIds.SpecularBakeElement
MaxPlus.ClassIds.Sphere
MaxPlus.ClassIds.Spheregizmo
MaxPlus.ClassIds.SphericalCollision
MaxPlus.ClassIds.Spline3d
MaxPlus.ClassIds.Splineikcontrol
MaxPlus.ClassIds.Splineshape
MaxPlus.ClassIds.SpotLight
MaxPlus.ClassIds.Srend
MaxPlus.ClassIds.Standin
MaxPlus.ClassIds.Star
MaxPlus.ClassIds.StdDualVertexShader
MaxPlus.ClassIds.StdRaytraceShadow
MaxPlus.ClassIds.StdShadowMap
MaxPlus.ClassIds.Stdbrushpresetcontext
MaxPlus.ClassIds.Stdshaders
MaxPlus.ClassIds.Stdtexout
MaxPlus.ClassIds.Stduv
MaxPlus.ClassIds.Stdxyz
MaxPlus.ClassIds.StraussShader
MaxPlus.ClassIds.SubExtrude
MaxPlus.ClassIds.Sunlight
MaxPlus.ClassIds.SurfControl
MaxPlus.ClassIds.Surfrevosm
MaxPlus.ClassIds.System
MaxPlus.ClassIds.TabDialogCustomize
MaxPlus.ClassIds.TabDialogEnvironment
MaxPlus.ClassIds.TabDialogPath
MaxPlus.ClassIds.TabDialogPreferences
MaxPlus.ClassIds.TabDialogProperties
MaxPlus.ClassIds.TabDialogRender
MaxPlus.ClassIds.TabDialogVideoPost
MaxPlus.ClassIds.Tapehelp
MaxPlus.ClassIds.Taperosm
MaxPlus.ClassIds.Targa
MaxPlus.ClassIds.Targapls
MaxPlus.ClassIds.Target
MaxPlus.ClassIds.TcbinterpFloat
MaxPlus.ClassIds.TcbinterpPoint3
MaxPlus.ClassIds.TcbinterpPoint4
MaxPlus.ClassIds.TcbinterpPosition
MaxPlus.ClassIds.TcbinterpRotation
MaxPlus.ClassIds.TcbinterpScale
MaxPlus.ClassIds.TdirLight
MaxPlus.ClassIds.Teapot
MaxPlus.ClassIds.Tee
MaxPlus.ClassIds.Tessellate
MaxPlus.ClassIds.Texmap
MaxPlus.ClassIds.TexmapContainer
MaxPlus.ClassIds.Texoutput
MaxPlus.ClassIds.Text
MaxPlus.ClassIds.TheGridref
MaxPlus.ClassIds.TheScene
MaxPlus.ClassIds.Tint
MaxPlus.ClassIds.ToneOperator
MaxPlus.ClassIds.Torus
MaxPlus.ClassIds.TrackSelectionSet
MaxPlus.ClassIds.TrackSelectionSetMgr
MaxPlus.ClassIds.Trackbar
MaxPlus.ClassIds.TrackviewUtility
MaxPlus.ClassIds.TreeView
MaxPlus.ClassIds.Triobj
MaxPlus.ClassIds.Tube
MaxPlus.ClassIds.Tvnode
MaxPlus.ClassIds.Twistosm
MaxPlus.ClassIds.Unwrap
MaxPlus.ClassIds.Userdatatype
MaxPlus.ClassIds.Utility
MaxPlus.ClassIds.UtilityPanelRollupcfg
MaxPlus.ClassIds.Uvgen
MaxPlus.ClassIds.UvwXform
MaxPlus.ClassIds.UvwXform2
MaxPlus.ClassIds.Uvwmaposm
MaxPlus.ClassIds.Vcol
MaxPlus.ClassIds.Vdm
MaxPlus.ClassIds.VideoPostTvnode
MaxPlus.ClassIds.Viewref
MaxPlus.ClassIds.WalledRectangle
MaxPlus.ClassIds.Waveobj
MaxPlus.ClassIds.WideFlange
MaxPlus.ClassIds.Windmod
MaxPlus.ClassIds.Windobject
MaxPlus.ClassIds.Wipe
MaxPlus.ClassIds.Wsd
MaxPlus.ClassIds.Wsm
MaxPlus.ClassIds.WsmDerivob
MaxPlus.ClassIds.WsmObject
MaxPlus.ClassIds.Xrefatmos
MaxPlus.ClassIds.Xrefctrl
MaxPlus.ClassIds.Xrefmaterial
MaxPlus.ClassIds.Xrefobj
MaxPlus.ClassIds.Xyzgen
MaxPlus.ClassIds.Yuv
MaxPlus.ClassIds.ZRenderElement
MaxPlus.ClassIds.__class__
MaxPlus.ClassIds.__del__
MaxPlus.ClassIds.__delattr__
MaxPlus.ClassIds.__dict__
MaxPlus.ClassIds.__doc__
MaxPlus.ClassIds.__format__
MaxPlus.ClassIds.__getattribute__
MaxPlus.ClassIds.__hash__
MaxPlus.ClassIds.__init__
MaxPlus.ClassIds.__module__
MaxPlus.ClassIds.__new__
MaxPlus.ClassIds.__reduce__
MaxPlus.ClassIds.__reduce_ex__
MaxPlus.ClassIds.__repr__
MaxPlus.ClassIds.__setattr__
MaxPlus.ClassIds.__sizeof__
MaxPlus.ClassIds.__str__
MaxPlus.ClassIds.__subclasshook__
MaxPlus.ClassIds.__swig_destroy__
MaxPlus.ClassIds.__weakref__
MaxPlus.ClassIds.thisown
"""
